'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def even_fibo():
    
    sum1, f, f1, f2 = 0, 0, 1, 1

    for i in range(2, 4000001):
        f = f1+f2
        if(f%2==0):
            sum1+=f

    print(sum1)

if __name__ == "__main__":
    even_fibo()
